/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gatepass;
import java.util.ArrayList;
import javax.swing.*;

/**
 *
 * @author 14367
 */
public class MainGUI extends javax.swing.JFrame {

    private ArrayList<GatePass> students = new ArrayList<GatePass>();
    private ArrayList<NormalGatePass> normalPass = new ArrayList<NormalGatePass>();
    private ArrayList<SeniorGatePass> seniorPass = new ArrayList<SeniorGatePass>();

    
    int counter = 0;
    /**
     * Creates new form MainGUI
     */
    public MainGUI() {
        initComponents();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        NewPassPanel = new javax.swing.JPanel();
        nameTL = new javax.swing.JLabel();
        gradeTL = new javax.swing.JLabel();
        idTL = new javax.swing.JLabel();
        commentsTL = new javax.swing.JLabel();
        submitButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        nameTF = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        idNumberTF = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        commentsTF = new javax.swing.JTextPane();
        isSeniorPassCheckBox = new javax.swing.JCheckBox();
        gradeNumberTF = new javax.swing.JTextField();
        seniorGatePassNumTL = new javax.swing.JLabel();
        seniorPassNumTF = new javax.swing.JTextField();
        gatePassesPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        recordsTable = new javax.swing.JTable();
        refreshButton = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();
        deleteMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentsMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nameTL.setText("Name");

        gradeTL.setText("Grade");

        idTL.setText("ID Number");

        commentsTL.setText("Comments");

        submitButton.setText("Submit");
        submitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                submitButtonMouseReleased(evt);
            }
        });
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        jScrollPane3.setViewportView(nameTF);

        jScrollPane4.setViewportView(idNumberTF);

        jScrollPane5.setViewportView(commentsTF);

        isSeniorPassCheckBox.setText("Senior Gate Pass");
        isSeniorPassCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isSeniorPassCheckBoxActionPerformed(evt);
            }
        });

        gradeNumberTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gradeNumberTFActionPerformed(evt);
            }
        });

        seniorGatePassNumTL.setText("Gate Pass #");

        seniorPassNumTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seniorPassNumTFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout NewPassPanelLayout = new javax.swing.GroupLayout(NewPassPanel);
        NewPassPanel.setLayout(NewPassPanelLayout);
        NewPassPanelLayout.setHorizontalGroup(
            NewPassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewPassPanelLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(NewPassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idTL)
                    .addComponent(nameTL)
                    .addComponent(gradeTL)
                    .addComponent(seniorGatePassNumTL)
                    .addComponent(commentsTL))
                .addGap(28, 28, 28)
                .addGroup(NewPassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NewPassPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(submitButton))
                    .addComponent(seniorPassNumTF, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(NewPassPanelLayout.createSequentialGroup()
                        .addComponent(gradeNumberTF, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(isSeniorPassCheckBox)))
                .addContainerGap(457, Short.MAX_VALUE))
        );
        NewPassPanelLayout.setVerticalGroup(
            NewPassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewPassPanelLayout.createSequentialGroup()
                .addGroup(NewPassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(submitButton)
                    .addGroup(NewPassPanelLayout.createSequentialGroup()
                        .addGroup(NewPassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(NewPassPanelLayout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(nameTL)
                                .addGap(7, 7, 7))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NewPassPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)))
                        .addGroup(NewPassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(gradeTL)
                            .addGroup(NewPassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(gradeNumberTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(isSeniorPassCheckBox)))
                        .addGap(7, 7, 7)
                        .addGroup(NewPassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idTL)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(NewPassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(seniorGatePassNumTL)
                            .addComponent(seniorPassNumTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(NewPassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(commentsTL)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(308, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("New GatePass", NewPassPanel);

        jScrollPane1.setOpaque(false);

        recordsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Name", "ID No.", "Grade", "Comments", "Senior Pass #"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        recordsTable.setGridColor(new java.awt.Color(0, 0, 0));
        recordsTable.setShowGrid(true);
        jScrollPane1.setViewportView(recordsTable);
        if (recordsTable.getColumnModel().getColumnCount() > 0) {
            recordsTable.getColumnModel().getColumn(0).setMinWidth(120);
            recordsTable.getColumnModel().getColumn(0).setMaxWidth(120);
            recordsTable.getColumnModel().getColumn(1).setMinWidth(70);
            recordsTable.getColumnModel().getColumn(1).setMaxWidth(70);
            recordsTable.getColumnModel().getColumn(2).setMinWidth(60);
            recordsTable.getColumnModel().getColumn(2).setMaxWidth(60);
            recordsTable.getColumnModel().getColumn(4).setMinWidth(80);
            recordsTable.getColumnModel().getColumn(4).setMaxWidth(80);
        }

        refreshButton.setText("refresh");
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout gatePassesPanelLayout = new javax.swing.GroupLayout(gatePassesPanel);
        gatePassesPanel.setLayout(gatePassesPanelLayout);
        gatePassesPanelLayout.setHorizontalGroup(
            gatePassesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gatePassesPanelLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 643, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(refreshButton)
                .addContainerGap(131, Short.MAX_VALUE))
        );
        gatePassesPanelLayout.setVerticalGroup(
            gatePassesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gatePassesPanelLayout.createSequentialGroup()
                .addGroup(gatePassesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gatePassesPanelLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(gatePassesPanelLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(refreshButton)))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Records", gatePassesPanel);

        fileMenu.setMnemonic('f');
        fileMenu.setText("File");

        openMenuItem.setMnemonic('o');
        openMenuItem.setText("Open");
        fileMenu.add(openMenuItem);

        saveMenuItem.setMnemonic('s');
        saveMenuItem.setText("Save");
        fileMenu.add(saveMenuItem);

        saveAsMenuItem.setMnemonic('a');
        saveAsMenuItem.setText("Save As ...");
        saveAsMenuItem.setDisplayedMnemonicIndex(5);
        fileMenu.add(saveAsMenuItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Edit");

        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("Cut");
        editMenu.add(cutMenuItem);

        copyMenuItem.setMnemonic('y');
        copyMenuItem.setText("Copy");
        editMenu.add(copyMenuItem);

        pasteMenuItem.setMnemonic('p');
        pasteMenuItem.setText("Paste");
        editMenu.add(pasteMenuItem);

        deleteMenuItem.setMnemonic('d');
        deleteMenuItem.setText("Delete");
        editMenu.add(deleteMenuItem);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        contentsMenuItem.setMnemonic('c');
        contentsMenuItem.setText("Contents");
        helpMenu.add(contentsMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        // TODO add your handling code here:

        if(isSeniorPassCheckBox.isSelected() == true){
            if(seniorPassNumTF.getText().equals("")){
                JOptionPane.showMessageDialog(this, "You need to enter the Senior gate pass number!");
            }
        }

        for(int row = 0; row < students.size(); row ++){ // this function will loop through the table while inputting data.

            if(isSeniorPassCheckBox.isSelected() == false){
                recordsTable.setValueAt(students.get(row).getName(), row, 0);  // row is obviously Y axis, while "0" "1" "2", etc would be X axis
                recordsTable.setValueAt(students.get(row).getId(), row, 1);
                recordsTable.setValueAt(students.get(row).getGrade(), row, 2);
                recordsTable.setValueAt(students.get(row).getComments(), row, 3);
            }

            else if(isSeniorPassCheckBox.isSelected() == true){
                recordsTable.setValueAt(students.get(row).getName(), row, 0);  // row is obviously Y axis, while "0" "1" "2", etc would be X axis
                recordsTable.setValueAt(students.get(row).getId(), row, 1);
                recordsTable.setValueAt(students.get(row).getGrade(), row, 2);
                recordsTable.setValueAt(students.get(row).getComments(), row, 3);

                SeniorGatePass s = (SeniorGatePass)(students.get(row));
                recordsTable.setValueAt(s.getPassNumber(), row, 4);
            }
        }
    }//GEN-LAST:event_refreshButtonActionPerformed

    private void seniorPassNumTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seniorPassNumTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seniorPassNumTFActionPerformed

    private void gradeNumberTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gradeNumberTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gradeNumberTFActionPerformed

    private void isSeniorPassCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isSeniorPassCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isSeniorPassCheckBoxActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_submitButtonActionPerformed

    private void submitButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitButtonMouseReleased
        // TODO add your handling code here:
        if(isSeniorPassCheckBox.isSelected()){ // this is a example of true polymorphism because i'm using a list
                                               // of the superclass GatePass but the individual objects are either
                                               // SeniorGatePass or NormalGatePass

            students.add(
                new SeniorGatePass(nameTF.getText(),
                    Integer.parseInt(gradeNumberTF.getText()),
                    Integer.parseInt(idNumberTF.getText()),
                    commentsTF.getText(),
                    Integer.parseInt(seniorPassNumTF.getText()),
                    isSeniorPassCheckBox.isSelected()));
        } // for if statement

        else{
            students.add(
                new NormalGatePass(nameTF.getText(),
                    Integer.parseInt(gradeNumberTF.getText()),
                    Integer.parseInt(idNumberTF.getText()),
                    commentsTF.getText()));
        }
        nameTF.setText("");
        gradeNumberTF.setText("");
        idNumberTF.setText("");
        commentsTF.setText("");
        seniorPassNumTF.setText("");
        isSeniorPassCheckBox.setSelected(false);
    }//GEN-LAST:event_submitButtonMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel NewPassPanel;
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JTextPane commentsTF;
    private javax.swing.JLabel commentsTL;
    private javax.swing.JMenuItem contentsMenuItem;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JMenuItem deleteMenuItem;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JPanel gatePassesPanel;
    private javax.swing.JTextField gradeNumberTF;
    private javax.swing.JLabel gradeTL;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JTextPane idNumberTF;
    private javax.swing.JLabel idTL;
    private javax.swing.JCheckBox isSeniorPassCheckBox;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JTextPane nameTF;
    private javax.swing.JLabel nameTL;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JMenuItem pasteMenuItem;
    private javax.swing.JTable recordsTable;
    private javax.swing.JButton refreshButton;
    private javax.swing.JMenuItem saveAsMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    private javax.swing.JLabel seniorGatePassNumTL;
    private javax.swing.JTextField seniorPassNumTF;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables

}
